<script setup>
import { useRoute } from 'vue-router'
import { computed } from 'vue'
import biman1 from '@/assets/images/product_service/biman.jpg'
import biman2 from '@/assets/images/product_service/biman2.jpg'
import biman3 from '@/assets/images/product_service/biman3.jpg'
import biman4 from '@/assets/images/product_service/biman4.png'
import biman5 from '@/assets/images/product_service/biman5.jpg'
import biman6 from '@/assets/images/product_service/biman6.jpg'
import biman7 from '@/assets/images/product_service/biman7.jpg'
import FreeDemonstration from '@/components/shared/FreeDemonstration/FreeDemonstration.vue'

const route = useRoute()

const softwareData = {
  AcousticSimulation: {
    title: 'Acoustic Simulation',
    description: 'There is virtually no field of engineering that remains untouched by acoustic simulation technology. The reason is simple: no industry can afford to deliver a product that is too loud or does not sound right. Sound quality is part of every product\'s identity and a key aspect of the brand and experience.Hexagon\'s acoustic simulation solutions have helped engineers across industries and around the world to meet increasingly stringent noise regulations or to guarantee that a new design is consistent with the trademark sound of the company. Where acoustic vibrations or noise generated by turbulent flow are involved, Hexagon\'s acoustic software is there to provide the right solution in the best simulation environment.',
    image: biman1,
    video: 'https://www.youtube.com/embed/7tVOeli-p8k?si=ICOU_tr5ejNGEcMc',
    softwareSolutions: [
      { name: 'Actran', color: 'from-blue-500 to-blue-700' },
      { name: 'MSC Nastran', color: 'from-cyan-500 to-teal-600' },
    ],
    cards: [
      {
        title: 'Advanced Modeling',
        desc: 'High accuracy sound and vibration modeling for industrial systems.',
        image: biman2,
      },
      {
        title: 'Noise Control',
        desc: 'Reduce unwanted noise and improve acoustic performance.',
        image: biman3,
      },
      {
        title: 'Simulation Tools',
        desc: 'Predict how products will sound in real-life environments.',
        image: biman4,
      },
      {
        title: 'Simulation Tools',
        desc: 'Predict how products will sound in real-life environments.',
        image: biman5,
      },
      {
        title: 'Simulation Tools',
        desc: 'Predict how products will sound in real-life environments.',
        image: biman6,
      },
    ],
  },
  'ComputerFluidDynamics': {
    title: 'Computer Fluid Dynamics',
    description: 'Computational fluid dynamics (CFD) is a simulation approach used for analyzing complex thermal and fluid phenomena. It is instrumental in ensuring the quality and safety of products used on a daily basis.CFD software is indispensable in early product development to ensure the best product concepts are identified early in the design process. Using CFD in the conceptual design phase improves design quality by conducting basic studies of fluid and thermal phenomena that directly affect product performance.Hexagon\'s computational fluid dynamics solutions enable users to visualize the complex movements of a gas or liquid flow in order to predict the performance of products before physical testing. They are particularly strong at coupled simulations, which allow the modelling of CFD results with other physics analysis such as mechanical and structural simulations. This results in a more optimized design early in the product development cycle. In some cases, CFD simulation can replace the need for physical testing.',
    image: biman2,
    video: 'https://www.youtube.com/embed/q_gFw7o8qCM?si=CmtuMTSiUomUz6f3',
    softwareSolutions: [
      { name: 'Cradle CFD', color: 'from-purple-500 to-purple-700' },
      { name: 'SC/Tetra', color: 'from-indigo-500 to-indigo-700' },
    ],
    cards: [
      {
        title: 'Flow Analysis',
        desc: 'Advanced computational fluid dynamics for complex systems.',
        image: biman1,
      },
      {
        title: 'Thermal Management',
        desc: 'Optimize heat transfer and cooling in product designs.',
        image: biman3,
      },
      {
        title: 'Multi-phase Flow',
        desc: 'Simulate interactions between different fluid phases.',
        image: biman4,
      },
      {
        title: 'Aerodynamic Design',
        desc: 'Improve aerodynamic performance and efficiency.',
        image: biman5,
      },
      {
        title: 'Turbulence Modeling',
        desc: 'Accurate prediction of turbulent flow behavior.',
        image: biman6,
      },
    ],
  },
  'ICME': {
    title: 'ICME',
    description: 'Sustainability requires true innovation in the connection of materials, manufacturing and product design.Hexagon\'s integrated computational materials engineering (ICME) tools serve as a low-cost, high-speed solution for minimizing the time, cost and risk associated with part design, material development/selection, processing optimization, performance simulation and production scaling.',
    image: biman3,
    video: 'https://www.youtube.com/embed/TIzzV7DLU8s?si=9xGq-SOm8OqIn_mW',
    softwareSolutions: [
      { name: 'Digimat', color: 'from-green-500 to-green-700' },
      { name: 'MaterialCenter', color: 'from-amber-500 to-amber-700' },
    ],
    cards: [
      {
        title: 'Material Modeling',
        desc: 'Comprehensive material behavior prediction and analysis.',
        image: biman1,
      },
      {
        title: 'Process Simulation',
        desc: 'Optimize manufacturing processes for material performance.',
        image: biman2,
      },
      {
        title: 'Multi-scale Analysis',
        desc: 'Bridge micro and macro material behavior.',
        image: biman4,
      },
      {
        title: 'Composite Design',
        desc: 'Advanced tools for composite material engineering.',
        image: biman5,
      },
      {
        title: 'Material Database',
        desc: 'Centralized material property management system.',
        image: biman7,
      },
    ],
  },
  'AutonomousSystem': {
    title: 'Autonomous System',
    description: 'With the rise of autonomous vehicles, automotive engineers face a new set of challenges. For example, the steering system is no longer required, so the vehicle chassis and suspension must be redesigned to prioritize passenger ride and comfort over steering and handling. Additionally, the increased number of sensors and electronics in autonomous vehicles requires careful thermal analysis to ensure their reliability and performance, as well as the safety of passengers. Finally, when passengers start to sleep, read books, or work on computers inside an autonomous vehicle, they become more sensitive to the acoustic environment, so infotainment system acoustics become a major differentiator for car manufacturers.MSC Software provides the most trusted CAE toolkits for automotive engineers to address these new challenges in the era of autonomous driving. From improving vehicle noise, vibration, and harshness (NVH) to increasing durability to reducing vehicle weight with new composite materials, MSC`s automotive solutions cover not only autonomous system development but also the design and construction of an entire new vehicle to meet the needs of autonomous driving.',
    image: biman4,
    video: 'https://www.youtube.com/embed/PopBc2-VFFw?si=kX7T2nLXOXetuoPt',
    softwareSolutions: [
      { name: 'VTD', color: 'from-purple-500 to-purple-700' },
      { name: 'VTD Scale', color: 'from-blue-500 to-blue-700' },
      { name: 'Cloud', color: 'from-gray-500 to-gray-700' },
    ],
    cards: [
      {
        title: 'Sensor Simulation',
        desc: 'Virtual testing of autonomous vehicle sensors.',
        image: biman1,
      },
      {
        title: 'Path Planning',
        desc: 'Advanced algorithms for autonomous navigation.',
        image: biman2,
      },
      {
        title: 'Virtual Testing',
        desc: 'Comprehensive simulation of autonomous scenarios.',
        image: biman3,
      },
      {
        title: 'Real-time Processing',
        desc: 'High-performance computing for autonomous decisions.',
        image: biman5,
      },
      {
        title: 'Safety Validation',
        desc: 'Ensure autonomous system reliability and safety.',
        image: biman6,
      },
    ],
  },
  'StructuralAnalysis': {
    title: 'Structural Analysis',
    description: 'Structural analysis software enables the creation of reliable and accurate digital twins of products and machines so engineers can design and invent next-generation devices. With physics-based engineering data under real-world operating conditions, engineers can dream of building greener planes and electric vehicles to sustain the planet, medical devices to save and improve human lives and next-generation spacecraft to allow exploration of space.FEA technology provides accurate simulation-based decision support and best practices selection for products. It gives engineers confidence that the final design will meet requirements before the physical product is built.Hexagon\'s structural analysis simulation tools leverage artificial intelligence (AI), machine learning (ML), high-performance computing (HPC), cloud and simulation processes and data management (SPDM) to address a variety of smart manufacturing challenges across automotive, aerospace, defense, renewable energy and life sciences.',
    image: biman5,
    video: 'https://www.youtube.com/embed/uwzf6GPMEX8?si=xvqYd0nHiZBIEEQ4',
    softwareSolutions: [
      { name: 'MSC Apex', color: 'from-red-500 to-red-700' },
      { name: 'Patran', color: 'from-orange-500 to-orange-700' },
      { name: 'Marc', color: 'from-blue-500 to-blue-700' },
      { name: 'Dytran', color: 'from-cyan-500 to-cyan-700' },
      { name: 'MSC Fatigue', color: 'from-teal-500 to-teal-700' },
    ],
    cards: [
      {
        title: 'FEA Analysis',
        desc: 'Advanced finite element analysis for structural integrity.',
        image: biman1,
      },
      {
        title: 'Stress Testing',
        desc: 'Comprehensive stress and strain analysis tools.',
        image: biman2,
      },
      {
        title: 'Dynamic Response',
        desc: 'Analyze structural behavior under dynamic loads.',
        image: biman3,
      },
      {
        title: 'Optimization',
        desc: 'Structural optimization for weight and performance.',
        image: biman4,
      },
      {
        title: 'Durability',
        desc: 'Predict product lifespan and fatigue performance.',
        image: biman6,
      },
    ],
  },
  'SystemDynamics': {
    title: 'System Dynamics',
    description: 'Dynamic system simulation must consider complex multibody interactions. Hexagon\'s system dynamics solutions offer system-level insight into movement, enabling CAE-led development of complex products with reduced prototyping and enhanced collaboration through workflows with other Hexagon and third-party tools.',
    image: biman6,
    video: 'https://hexagonmetrology.wistia.com/medias/ra6ctztodk?wvideo=ra6ctztodk',
    softwareSolutions: [
      { name: 'ADAMS', color: 'from-blue-500 to-blue-700' },
      { name: 'Easy5', color: 'from-yellow-500 to-yellow-700' },
      { name: 'Elements', color: 'from-red-500 to-red-700' },
      { name: 'Romax', color: 'from-orange-500 to-orange-700' },
    ],
    cards: [
      {
        title: 'Multi-body Dynamics',
        desc: 'Simulate complex mechanical system interactions.',
        image: biman1,
      },
      {
        title: 'Motion Analysis',
        desc: 'Comprehensive motion and mechanism simulation.',
        image: biman2,
      },
      {
        title: 'Control Systems',
        desc: 'Integrate control systems with mechanical dynamics.',
        image: biman3,
      },
      {
        title: 'Vehicle Dynamics',
        desc: 'Specialized tools for automotive system dynamics.',
        image: biman4,
      },
      {
        title: 'Real-time Simulation',
        desc: 'High-speed dynamic system simulation capabilities.',
        image: biman5,
      },
    ],
  },
  'VirtualManufacturing': {
    title: 'Virtual Manufacturing',
    description: 'Manufacturers are under increased pressure to maintain their competitive advantage by reducing product development time and cost while ensuring high-quality products. For example, in the automotive industry, vehicle development and production planning can be responsible for up to 90% of the total cost.Introducing virtual manufacturing and costing simulation tools in forming, welding, joining and stamping enables robust, error-free economic processes. Replacing physical product and process testing with virtual analysis and validations drastically reduces the production costs of prototypes and engineering proof time.Hexagon\'s virtual manufacturing and costing solutions support product developers through cost, design and manufacturing engineering. They enable engineers to prove manufacturability and validate production processes with simulation to achieve efficient and cost-effective product development and implementation.',
    image: biman7,
    video: 'https://www.youtube.com/embed/wgPiWnmWmRU?si=G_CfA43-zdhbAuEo',
    softwareSolutions: [
      { name: 'FTI FormingSuite', color: 'from-purple-500 to-purple-700' },
      { name: 'Simufact Welding', color: 'from-red-500 to-red-700' },
      { name: 'Simufact Joining', color: 'from-blue-500 to-blue-700' },
      { name: 'Simufact Forming', color: 'from-green-500 to-green-700' },
      { name: 'Simufact Additive', color: 'from-orange-500 to-orange-700' },
    ],
    cards: [
      {
        title: 'Process Simulation',
        desc: 'Virtual manufacturing process optimization.',
        image: biman1,
      },
      {
        title: 'Cost Analysis',
        desc: 'Manufacturing cost prediction and optimization.',
        image: biman2,
      },
      {
        title: 'Forming Simulation',
        desc: 'Metal forming and stamping process analysis.',
        image: biman3,
      },
      {
        title: 'Welding Analysis',
        desc: 'Comprehensive welding process simulation.',
        image: biman4,
      },
      {
        title: 'Additive Manufacturing',
        desc: '3D printing process simulation and optimization.',
        image: biman5,
      },
    ],
  },
}

const currentSoftware = computed(() => softwareData[route.params.slug])
</script>

<template>
  <section v-if="currentSoftware" class="p-8">
    <!-- Heading -->

<div class="text center mx-[250px] items-center ">
  <h1 class="text-4xl font-bold mb-6 flex text-center justify-center items-center bg-[#0b294b] text-white px-6 py-4 rounded-t-md">{{ currentSoftware.title }}</h1>
  <p class="text-xl">{{ currentSoftware.description }}</p>
</div>
    <!-- Image -->
    <div class="relative mx-[350px] mb-6 py-10">
      <img
        :src="currentSoftware.image"
        :alt="currentSoftware.title"
        class="w-full h-full object-cover rounded-xl shadow"
      />
    </div>
 <!-- Software Solutions -->
    <div class="max-w-6xl mx-auto my-16 text-center">
      <h2
        class="text-3xl font-bold mb-8 inline-block bg-[#0b294b] text-white px-8 py-5 rounded-xl"
      >
        Software Solutions
      </h2>

      <div class="flex flex-wrap justify-center gap-6 mt-6">
        <div
          v-for="(softwareSolution, index) in currentSoftware.softwareSolutions"
          :key="index"
          :class="[
            'py-4 px-8 text-white font-semibold text-md rounded-2xl shadow-md hover:shadow-xl transition-transform transform hover:-translate-y-1 cursor-pointer bg-gradient-to-br',
            softwareSolution.color,
          ]"
        >
          {{ softwareSolution.name }}
        </div>
      </div>
    </div>

    <!-- Video -->
    <div class=" mx-[350px] my-10">
      <iframe
        :src="currentSoftware.video"
        class="w-full h-[450px] rounded-xl shadow-lg"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
      ></iframe>
    </div>



    <!-- Case Study Title -->
    <div class="max-w-6xl mx-auto text-center ">
      <h2
        class="text-3xl font-bold mb-8 inline-block bg-[#0b294b] text-white px-8 py-5 rounded-xl"
      >
        Case Study
      </h2>
    </div>

    <!-- Marquee Cards Section -->
    <div class="overflow-hidden relative py-10 bg-gradient-to-r from-orange-50 to-indigo-50">
      <div
        class="flex gap-8 animate-marquee hover:[animation-play-state:paused] px-60"
      >
        <div
          v-for="(card, index) in currentSoftware.cards"
          :key="index"
          class="min-w-[300px] max-w-sm bg-white rounded-2xl overflow-hidden shadow-lg hover:shadow-2xl transform hover:-translate-y-2 transition-all duration-300"
        >
          <img
            :src="card.image"
            alt="Card Image"
            class="w-full h-48 object-cover"
          />
          <div class="p-6">
            <h3
              class="text-xl font-bold text-gray-800 mb-2 group-hover:text-indigo-600"
            >
              {{ card.title }}
            </h3>
            <p class="text-gray-600 mb-4 text-sm leading-relaxed">
              {{ card.desc }}
            </p>
            <a
              href="#"
              class="inline-block bg-indigo-600 text-white text-sm font-medium py-2 px-4 rounded-full hover:bg-indigo-700 transition"
            >
              Learn More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <p v-else class="text-center text-red-500 mt-10">Software not found.</p>

  <FreeDemonstration />
</template>

<style scoped>
@keyframes marquee {
  0% {
    transform: translateX(0%);
  }
  100% {
    transform: translateX(-50%);
  }
}

.animate-marquee {
  display: flex;
  animation: marquee 6s linear infinite;
}
.animate-marquee :hover{
  animation-play-state: paused;
}
</style>
