<template>
  <div class="max-w-6xl mx-auto p-6 space-y-3">
    <div class="flex items-center justify-between">
        <button
                class="inline-flex items-center gap-2 border border-gray-300 px-6 py-2.5 rounded-lg text-gray-700 font-medium hover:bg-gray-50 transition-colors"
            @click="$router.back()"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
            </svg>
            Back to Reports
          </button>
          <button
          v-if="!loading"
            class="bg-red-600 text-white px-6 py-2 rounded"
            @click="generatePDF"
          >
            Download PDF
          </button>
    </div>
    <!-- Loading State -->
    <div v-if="loading" class="flex justify-center items-center min-h-[400px]">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
    </div>

    <!-- Content -->
    <div v-else ref="printArea" class="print-area space-y-3">
      <!-- Header Card -->
      <div class="bg-white border border-gray-200 rounded-xl shadow-sm p-8">
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
          <div>

            <h1 class="text-3xl font-bold text-gray-900">
              Success Team Activity Report
            </h1>
            <div class="flex items-center gap-2 mt-2">
              <span class="inline-flex items-center gap-1.5 text-sm text-gray-600">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path>
                </svg>
                {{ report?.success_team?.name }}
              </span>
              <span class="text-gray-400">•</span>
              <span class="text-sm font-medium text-primary">
                {{ report?.period }}
              </span>
            </div>
          </div>

          <span
            class="inline-flex items-center px-4 py-2 rounded-full text-sm font-semibold"
            :class="statusClass(report?.status)"
          >
            <span class="w-2 h-2 rounded-full mr-2" :class="statusDotClass(report?.status)"></span>
            {{ statusText(report?.status) }}
          </span>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 pt-6 border-t border-gray-100">
          <div class="space-y-1">
            <p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Generated By</p>
            <p class="text-lg font-semibold text-gray-900">{{ report?.user?.name }}</p>
            <p class="text-sm text-gray-600">{{ report?.user?.email }}</p>
            <p class="text-xs text-gray-500 capitalize">{{ formatRole(report?.user?.role) }}</p>
          </div>

          <div class="space-y-1">
            <p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Success Team</p>
            <p class="text-lg font-semibold text-gray-900">{{ report?.success_team?.name }}</p>
            <p class="text-sm text-gray-600">Team ID: {{ report?.success_team?.id }}</p>
          </div>

          <div class="space-y-1">
            <p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Report Date</p>
            <p class="text-lg font-semibold text-gray-900">{{ formatDateTime(report?.created_at) }}</p>
            <p class="text-sm text-gray-600">Period: {{ report?.period }}</p>
          </div>
        </div>
      </div>

      <!-- Summary Stats -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div class="bg-gradient-to-br from-blue-50 to-blue-100 border border-blue-200 rounded-xl p-6">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-blue-700">Total Activities</p>
              <p class="text-3xl font-bold text-blue-900 mt-2">{{ outputs.length }}</p>
            </div>
            <div class="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center">
              <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path>
              </svg>
            </div>
          </div>
        </div>

        <div class="bg-gradient-to-br from-green-50 to-green-100 border border-green-200 rounded-xl p-6">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-green-700">Completed</p>
              <p class="text-3xl font-bold text-green-900 mt-2">{{ completedCount }}</p>
            </div>
            <div class="w-12 h-12 bg-green-600 rounded-lg flex items-center justify-center">
              <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
              </svg>
            </div>
          </div>
        </div>

        <div class="bg-gradient-to-br from-purple-50 to-purple-100 border border-purple-200 rounded-xl p-6">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-purple-700">Unique Tasks</p>
              <p class="text-3xl font-bold text-purple-900 mt-2">{{ groupedOutputs.length }}</p>
            </div>
            <div class="w-12 h-12 bg-purple-600 rounded-lg flex items-center justify-center">
              <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
              </svg>
            </div>
          </div>
        </div>

        <div class="bg-gradient-to-br from-amber-50 to-amber-100 border border-amber-200 rounded-xl p-6">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-amber-700">Completion Rate</p>
              <p class="text-3xl font-bold text-amber-900 mt-2">
                {{ completionRate }}%
              </p>
            </div>
            <div class="w-12 h-12 bg-amber-600 rounded-lg flex items-center justify-center">
              <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
              </svg>
            </div>
          </div>
        </div>
      </div>

      <!-- Activities Section -->
      <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
        <div class="px-8 py-6 border-b border-gray-100">
          <div class="flex items-center justify-between">
            <div>
              <h2 class="text-xl font-bold text-gray-900">Activity Logs</h2>
              <p class="text-sm text-gray-600 mt-1">Detailed breakdown of all activities for the reporting period</p>
            </div>
            <div class="flex items-center gap-2 text-sm text-gray-500">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
              </svg>
              {{ report?.period }}
            </div>
          </div>
        </div>

        <div class="p-8">
          <div v-if="groupedOutputs.length" class="space-y-8">
            <div
              v-for="group in groupedOutputs"
              :key="group.task_id"
              class="border border-gray-200 rounded-xl overflow-hidden hover:shadow-lg transition-shadow duration-200"
            >
              <!-- Task Header -->
              <div class="bg-gray-50 px-6 py-4 border-b border-gray-200">
                <div class="flex flex-col lg:flex-row lg:items-center justify-between gap-3">
                  <div class="flex items-center gap-3">
                    <div class="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center">
                      <svg class="w-5 h-5 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                      </svg>
                    </div>
                    <div>
                      <h3 class="font-semibold text-gray-900 text-lg">{{ group.task_name }}</h3>
                      <div class="flex flex-wrap items-center gap-3 mt-1">
                        <span class="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                          <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
                          </svg>
                          {{ group.task_type }}
                        </span>
                        <span class="text-sm text-gray-600">
                          <span class="text-gray-500">Assigned to:</span>
                          <span class="font-medium ml-1">{{ group.assigned_to_name }}</span>
                        </span>
                      </div>
                    </div>
                  </div>
                  <span class="px-4 py-1.5 rounded-full text-sm font-medium capitalize"
                    :class="group.task_status === 'pending'
                      ? 'bg-amber-100 text-amber-800'
                      : group.task_status === 'completed'
                        ? 'bg-green-100 text-green-800'
                        : 'bg-gray-100 text-gray-800'">
                    {{ group.task_status }}
                  </span>
                </div>
              </div>

              <!-- Activity Table -->
              <div class="overflow-x-auto">
                <table class="w-full">
                  <thead class="bg-gray-50">
                    <tr>
                      <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Date</th>
                      <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Activity Output</th>
                      <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Status</th>
                      <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Completed On</th>
                      <!-- <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Actions</th> -->
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200">
                    <tr v-for="output in group.outputs" :key="output.id" class="hover:bg-gray-50 transition-colors">
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                          <div class="w-2 h-2 rounded-full bg-primary mr-2"></div>
                          <span class="text-sm font-medium text-gray-900">{{ formatDate(output.date) }}</span>
                        </div>
                      </td>
                      <td class="px-6 py-4">
                        <div class="max-w-lg">
                          <p class="text-sm text-gray-900">{{ output.output }}</p>
                          <p class="text-xs text-gray-500 mt-1">
                            Updated: {{ formatDateTime(output.updated_at) }}
                          </p>
                        </div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium"
                          :class="output.status === '1'
                            ? 'bg-green-100 text-green-800'
                            : 'bg-gray-100 text-gray-800'">
                          <span class="w-1.5 h-1.5 rounded-full mr-1.5"
                            :class="output.status === '1' ? 'bg-green-500' : 'bg-gray-500'"></span>
                          {{ output.status === '1' ? 'Completed' : 'Pending' }}
                        </span>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div v-if="output.completed_at" class="flex items-center text-sm text-gray-900">
                          <svg class="w-4 h-4 mr-1.5 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                          </svg>
                          {{ formatDate(output.completed_at) }}
                        </div>
                        <span v-else class="text-sm text-gray-400">—</span>
                      </td>
                      <!-- <td class="px-6 py-4 whitespace-nowrap">
                        <button
                          @click="viewActivityDetails(output)"
                          class="text-primary hover:text-primary-dark text-sm font-medium flex items-center gap-1">
                          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
                          </svg>
                          View Details
                        </button>
                      </td> -->
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <!-- Empty State -->
          <div v-else class="text-center py-12">
            <div class="mx-auto w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4">
              <svg class="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
              </svg>
            </div>
            <h3 class="text-lg font-medium text-gray-900 mb-2">No Activities Found</h3>
            <p class="text-gray-600 max-w-md mx-auto">
              There are no activity logs recorded for the {{ report?.period }} reporting period.
            </p>
          </div>
        </div>
      </div>

      <!-- Footer Actions -->
      <div class="flex flex-col sm:flex-row justify-between items-center gap-4 pt-4">
        <div class="text-sm text-gray-600">
          Report ID: {{ report?.id }} • Generated on {{ formatDateTime(report?.created_at) }}
        </div>
        <!-- <div class="flex gap-3">
          <button
            class="inline-flex items-center gap-2 border border-gray-300 px-6 py-2.5 rounded-lg text-gray-700 font-medium hover:bg-gray-50 transition-colors"
            @click="$router.back()"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
            </svg>
            Back to Reports
          </button>

          <button
            class="inline-flex items-center gap-2 bg-primary text-white px-6 py-2.5 rounded-lg font-medium hover:bg-primary-dark transition-colors"
            @click="printReport"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path>
            </svg>
            Print Report
          </button>

          <button
            v-if="report?.status === '0'"
            class="inline-flex items-center gap-2 bg-green-600 text-white px-6 py-2.5 rounded-lg font-medium hover:bg-green-700 transition-colors"
            @click="submitReport"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
            Submit Report
          </button>
        </div> -->
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue'
import { useRoute } from 'vue-router'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

const printArea = ref()
const route = useRoute()
const loading = ref(true)

const report = ref(null)
const outputs = ref([])

onMounted(() => {
  fetchReport()
})

async function fetchReport() {
  loading.value = true
  try {
    // Your existing API call
    const { data } = await api().get(
      `/success-team-activity-reports/${route.params.id}`
    )

    report.value = data.report
    outputs.value = data.outputs
  } catch (error) {
    console.error('Error fetching report:', error)
    // Handle error appropriately
  } finally {
    loading.value = false
  }
}

/* -------- Computed Properties -------- */
const groupedOutputs = computed(() => {
  const map = {}

  outputs.value.forEach(output => {
    const task = output.success_team_task
    if (!task) return

    const taskId = task.id

    if (!map[taskId]) {
      map[taskId] = {
        task_id: taskId,
        task_name: task.description || 'Unnamed Task',
        task_type: task.type || 'General',
        task_status: task.status || 'pending',
        assigned_to_name: task.assigned_person?.name || 'Unassigned',
        assigned_to_email: task.assigned_person?.email || '',
        outputs: []
      }
    }

    map[taskId].outputs.push(output)
  })

  // Sort outputs by date descending
  Object.values(map).forEach(group => {
    group.outputs.sort((a, b) => new Date(b.date) - new Date(a.date))
  })

  return Object.values(map)
})

const completedCount = computed(() => {
  return outputs.value.filter(output => output.status === '1').length
})

const completionRate = computed(() => {
  if (outputs.value.length === 0) return 0
  return Math.round((completedCount.value / outputs.value.length) * 100)
})

/* -------- Helper Functions -------- */
const statusText = (status) => ({
  '0': 'Draft',
  '1': 'Submitted',
  '2': 'Approved'
}[status] || 'Unknown')

const statusClass = (status) => ({
  '0': 'bg-gray-100 text-gray-800',
  '1': 'bg-blue-100 text-blue-800',
  '2': 'bg-green-100 text-green-800'
}[status] || 'bg-gray-100 text-gray-800')

const statusDotClass = (status) => ({
  '0': 'bg-gray-500',
  '1': 'bg-blue-500',
  '2': 'bg-green-500'
}[status] || 'bg-gray-500')

const formatDate = (dateString) => {
  if (!dateString) return '—'
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

const formatDateTime = (dateTimeString) => {
  if (!dateTimeString) return '—'
  const date = new Date(dateTimeString)
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const formatRole = (role) => {
  if (!role) return ''
  return role.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
}

/* -------- Action Functions -------- */
const viewActivityDetails = (output) => {
  // Implement modal or detailed view for activity
  console.log('View activity details:', output)
  // You can open a modal or navigate to a detailed view
}


const generatePDF = async () => {
  const element = printArea.value

  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: '#ffffff',
    useCORS: true,

    onclone: (clonedDoc) => {

      // Force safe colors on cloned document
      const style = clonedDoc.createElement('style')

      style.innerHTML = `
        * {
          color: rgb(0,0,0) !important;
          background-color: rgb(255,255,255) !important;
          border-color: rgb(200,200,200) !important;
          box-shadow: none !important;
        }

        .bg-primary {
          background-color: rgb(59,130,246) !important;
        }

        .text-primary {
          color: rgb(59,130,246) !important;
        }
      `

      clonedDoc.head.appendChild(style)
    }
  })

  const imgData = canvas.toDataURL('image/png')

  const pdf = new jsPDF('p', 'mm', 'a4')

  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()

  const imgWidth = pageWidth
  const imgHeight = canvas.height * imgWidth / canvas.width

  let heightLeft = imgHeight
  let position = 0

  pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)

  heightLeft -= pageHeight

  while (heightLeft > 0) {
    position = heightLeft - imgHeight
    pdf.addPage()
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
    heightLeft -= pageHeight
  }

  pdf.save(`success-team-report-${report.value?.id}.pdf`)
}

const printSection = () => {
    const content = printArea.value.innerHTML

  const win = window.open('', '', 'width=900,height=650')

  win.document.write(`
    <html>
      <head>
        <title>Print</title>
      </head>
      <body>
        ${content}
      </body>
    </html>
  `)

  win.document.close()
  win.print()
}
</script>

<style scoped>
@media print {
  button,
  .no-print {
    display: none !important;
  }

  .max-w-6xl {
    max-width: none !important;
  }

  .border {
    border: 1px solid #e5e7eb !important;
  }

  .shadow-sm {
    box-shadow: none !important;
  }

  .bg-gradient-to-br {
    background: #f9fafb !important;
  }
}

@media print {

  body * {
    visibility: hidden;
  }

  .print-area,
  .print-area * {
    visibility: visible;
  }

  .print-area {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;

  }

}

</style>
