
import { defineStore } from 'pinia';

export const useAccountDetailsStore = defineStore('accountDetails', {
  state: () => ({
   salesOverview: [
  { name: "SSEM Communication Schedule" },
  { name: "SSEM Call Experience" },
  { name: "Sales Executive Caller (SEC)" },
  { name: "Group Name" },
  { name: "Sales Executive Last Call Date (SEC)" },
  { name: "Sales Executive Marks (SEC)" },
  { name: "Lead Sales Executive (SEC)" },
  { name: "Account Name" },
  { name: "Customer Parent Company Name" },
  { name: "Account Level" },
  { name: "Deal Status" },
  { name: "Amount Potential Status" },
  { name: "Sales Completion Targets Data" },
  { name: "Proposal Pregener" },
  { name: "Proposal Reviewer Completion Data" },
  { name: "Sales Target Year - Quarter" },
  { name: "Legal Source" },
  { name: "Sub Industry Name" },
  { name: "Honours - Dodge Industry Name" },
  { name: "SSEM Work Notes" },
  { name: "SSEM Communication Schedule" },
  { name: "Account Reviewer" },
  { name: "Sales Executive Call Bank Schedule (SEC)" },
  { name: "Sales Executive Last Mark Index (SEC)" },
  { name: "Most Step Summary" },
  { name: "Last Email Date" },
  { name: "Customer Know Company Aks" },
  { name: "CEO's Deal Review Data" },
  { name: "Lead Priority" },
  { name: "Deal Potential Status" },
  { name: "Last Amount Review Data" },
  { name: "Closing Date" },
  { name: "Proposal Reviewer Name" },
  { name: "Latest Proposal Submission Date" },
  { name: "Original Data Input Data" },
  { name: "Industry" },
  { name: "Dodge Industry Sub-sale Lines Name" },
  { name: "Payment Received Date" }
],
projectOverview :[
  { name: "Project Author" },
  { name: "Project Cost" },
  { name: "Construction End Date" },
  { name: "Construction Start Date" },
  { name: "Please/CFBusiness/Actions" },
  { name: "tags/Tips" },
  { name: "BulldogCategory/Conciton" },
  { name: "ction/Types" },
  { name: "Project Summary" },
  { name: "Project Description" },
  { name: "Meta and Metas" },
  { name: "Biling Country" },
  { name: "Biling City" },
  { name: "Biling State" },
  { name: "Biling County" },
  { name: "Biling 2ip Code" },
  { name: "Biling Street" }
],
 ownerDetails :[
  { name: "Owner Company Name" },
  { name: "Owner City" },
  { name: "Owner Address" },
  { name: "Owner Contact Name" },
  { name: "Owner Contact Title" },
  { name: "Owner Phone" },
  { name: "Owner Fax" },
  { name: "Owner Location Phone 1" },
  { name: "Owner Sticks" },
  { name: "Owner Website" },
  { name: "Owner State" },
  { name: "Owner E-Mail" },
  { name: "Owner Contact Name 2" },
  { name: "Owner Contact Title 2" },
  { name: "Owner Phone 2" },
  { name: "Owner Location Phone 2" }
],
architectDetails : [
  { name: "Architect Company Name" },
  { name: "Architect Contact Name" },
  { name: "Architect Contact Title" },
  { name: "Architect Phone" },
  { name: "Architect Location Phone 1" },
  { name: "Architect Address" },
  { name: "Architect Website" },
  { name: "Architect Contact Name 2" },
  { name: "Architect Contact Title 2" },
  { name: "Architect Phone 2" },
  { name: "Architect Location Phone 1" }
],
contractorDetails : [
  { name: "GC Company Alone" },
  { name: "GC Contract Alone 1" },
  { name: "GC Contract Title 1" },
  { name: "GC Phone 1" },
  { name: "GC E-Mail" },
  { name: "GC Strike" },
  { name: "GC Location Phone 1" },
  { name: "GC Company MobileTes" },
  { name: "GC Contract Alone 2" },
  { name: "GC Contract Title 2" },
  { name: "GC Phone 2" },
  { name: "GC City" },
  { name: "GC Zip Code" },
  { name: "GC Location Phone 2" }
],
developerDetails :[
  { name: "Developer Category Name" },
  { name: "Developer Contact Name 1" },
  { name: "Developer Contact Title 1" },
  { name: "Developer Phone 1" },
  { name: "Developer E-Mail" },
  { name: "Developer State" },
  { name: "Developer Location Phone 1" },
  { name: "Developer Category Website" },
  { name: "Developer Contact Name 2" },
  { name: "Developer Contact Title 2" },
  { name: "Developer Phone 2" },
  { name: "Developer City" },
  { name: "Developer Zip Code" },
  { name: "Developer Location Phone 3" }
],
   summaryPage: [
      { name: "Account Name", value: "Acme Corporation" },
      { name: "Project Number", value: "PRJ-" + Math.floor(Math.random() * 10000) },
      { name: "Customer Parent Company Name", value: "Global Holdings Inc." },
      { name: "Project Cost", value: "$" + (Math.random() * 1000000).toFixed(2) },
      { name: "Construction End Date", value: new Date(Date.now() + Math.random() * 10000000000).toLocaleDateString() },
      { name: "Construction Start Date", value: new Date(Date.now() - Math.random() * 10000000000).toLocaleDateString() },
      { name: "Project Description", value: "New corporate headquarters building with sustainable design features" },
      { name: "News and Notes", value: "Priority client - VIP treatment required" },
      { name: "Billing State", value: ["CA", "NY", "TX", "FL"][Math.floor(Math.random() * 4)] },
      { name: "Billing City", value: ["New York", "Los Angeles", "Chicago", "Houston"][Math.floor(Math.random() * 4)] },
      { name: "Owner Company Name", value: "Property Ventures LLC" },
      { name: "Project Summary", value: "45-story mixed-use development in downtown" },
      { name: "Owner Contact Name", value: "John Smith" },
      { name: "Owner Contact Name 2", value: "Sarah Johnson" },
      { name: "Owner Contact Title", value: "Director of Operations" },
      { name: "Owner Contact Title 2", value: "Project Manager" },
      { name: "Owner Phone", value: "(555) " + Math.floor(100 + Math.random() * 900) + "-" + Math.floor(1000 + Math.random() * 9000) },
      { name: "Owner Phone 2", value: "(555) " + Math.floor(100 + Math.random() * 900) + "-" + Math.floor(1000 + Math.random() * 9000) },
      { name: "Owner Fax", value: "(555) " + Math.floor(100 + Math.random() * 900) + "-" + Math.floor(1000 + Math.random() * 9000) },
      { name: "Owner E-Mail", value: "contact@" + ["acme", "global", "property"].map(x => x + ".com")[Math.floor(Math.random() * 3)] },
      { name: "Owner Location Phone 1", value: "(555) " + Math.floor(100 + Math.random() * 900) + "-" + Math.floor(1000 + Math.random() * 9000) },
      { name: "Owner Location Phone 2", value: "(555) " + Math.floor(100 + Math.random() * 900) + "-" + Math.floor(1000 + Math.random() * 9000) }
    ]
  }),
  actions: {
    updateField(fieldName, newValue) {
      const field = this.summaryPage.find(f => f.name === fieldName);
      if (field) {
        field.value = newValue;
      }
    }
  },

});
